default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: admon
  host: 127.0.0.1
  port: 3307
  ssl_mode: DISABLED

development:
  <<: *default
  database: bodega_development

test:
  <<: *default
  database: bodega_test

production:
  primary: &primary_production
    <<: *default
    database: bodega_production
    username: bodega
    password: <%= ENV["BODEGA_DATABASE_PASSWORD"] %>

  cache:
    <<: *primary_production
    database: bodega_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: bodega_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: bodega_production_cable
    migrations_paths: db/cable_migrate
